#spring:
#  security:
#    user:
#      name: admin
#      password: admin


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/linfq
    username: linfq
    password: linfq
    type: com.alibaba.druid.pool.DruidDataSource